steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/gcp-exemplo/live-ci-cd:latest', '-t', 'gcr.io/gcp-exemplo/live-ci-cd:$SHORT_SHA','.']

  - name: 'docker'
    args: ['run','-d','--name','goapp','gcr.io/gcp-exemplo/live-ci-cd:latest']

  - name: 'docker'
    args: ['exec','goapp','go','test']